# -*- coding: UTF-8 -*-
from django.contrib import admin
from models import *

admin.site.register(geo)
admin.site.register(hCard)
admin.site.register(adr_type)
admin.site.register(adr)
admin.site.register(tel_type)
admin.site.register(tel)
admin.site.register(email_type)
admin.site.register(email)
admin.site.register(photo)
admin.site.register(logo)
admin.site.register(sound)
admin.site.register(title)
admin.site.register(role)
admin.site.register(org)
admin.site.register(note)
admin.site.register(key)
admin.site.register(mailer)
admin.site.register(hCalendar)
admin.site.register(xfn_values)
admin.site.register(xfn)
admin.site.register(hListing)
admin.site.register(hReview)
